### ISSUE TITLE
Get an "incorrect audio shape" assert when I process the whisper models

### ISSUE THREAD

**Issue by jasontitus** [wangchou/callCoreMLFromCpp#1]
When trying to convert the whisper models I get an assert - 

  assert x.shape[1:] == self.positional_embedding.shape, "incorrect audio shape"

It doesn't seem to kill the process, but the produced models don't seem to recognize much of anything (one word of the JFK sample, for example), and are different from the models others uploaded to HF.  I'm running this on  a Macbook Pro M2 64GB - Mac OS 13.3.

**Comment by wangchou** [comment]
That means ... there is a warning on that assert line. 
That assert didn't get fired.

About how to use the encoder model, please check https://github.com/ggerganov/whisper.cpp/pull/566 .

```
/projects/w/whisper/whisper/model.py:166: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data
flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1:] == self.positional_embedding.shape, "incorrect audio shape"
```
